#!/bin/bash

# Sleep to allow Elasticsearch to finish initializing
# if it's not done doing whatever it does yet
echo "Waiting for Elasticsearch"

until wget -qO - $ELASTICSEARCH_HOST; do
  echo "."
  sleep 2
done

# Workaround for elasticsearch watermark check not working as expected within docker containers using autogrow s3 storage containers
curl -XPUT 'elasticsearch:9200/_cluster/settings' -H 'Content-Type: application/json' -d'
{
    "transient": {
        "cluster.routing.allocation.disk.watermark.low": "15gb",
        "cluster.routing.allocation.disk.watermark.high": "10gb",
        "cluster.routing.allocation.disk.watermark.flood_stage": "5gb",
        "cluster.info.update.interval": "1m"
    }
}
'

sleep 10

echo -n "Waiting for Postgres"

while ! nc -z $POSTGRES_HOST $POSTGRES_PORT; do
  echo "."
  sleep 2
done

echo ""

if [[ $MIX_ENV == "dev" ]]; then
  /bin/run-development
  exit $?
fi

#mix ecto.load -r Philomena.Repo -d priv/repo/structure.sql --skip-if-loaded
#mix ecto.migrate -r Philomena.Repo

mix reindex_all

# Get local IP
PHILO_POD_IP=$(ip route get 1.1.1.1 | head -1 | cut -d' ' -f7)

echo "Starting Philomena with IP $PHILO_POD_IP"

/srv/philomena/_build/prod/rel/philomena/bin/philomena start
